language: objective-c
osx_image: xcode7.3

before_install:
  - gem install cocoapods -v '1.0.0'

install:
  - gem install xcpretty

script:
  - set -o pipefail
  - pod install
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild -workspace GABoardGameGeek.xcworkspace -scheme GABoardGameGeek -sdk iphonesimulator9.3 -destination 'OS=9.3,name=iPhone 6S Plus' test | xcpretty

after_success:
  - bash <(curl -s https://codecov.io/bash)