# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode7.3
language: objective-c
cache: cocoapods
podfile: Example/Podfile

before_install:
 - gem install cocoapods # Since Travis is not always on latest version
 - pod install --project-directory=Example --verbose --repo-update

script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild test -workspace Example/GABoardGameGeek.xcworkspace -scheme GABoardGameGeek-Example -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=YES | xcpretty

after_success:
  - bash <(curl -s https://codecov.io/bash)
