language: objective-c
osx_image: xcode7.3

install:
  - gem install xcpretty

script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild -project GABoardGameGeek.xcodeproj -scheme GABoardGameGeek -sdk iphonesimulator9.3 -destination 'OS=9.3,name=iPhone 6S Plus' test | xcpretty

after_success:
  - bash <(curl -s https://codecov.io/bash)